#!/usr/bin/env bash
set +vx
# show - Manage browser (and php server if applicable)
# Started by lxsession's autostart, can be managed manually.
# Environmental variables can override the baked-in settings:
# - SITE for the web server
# - URL for the browser
# Required: procps(pkill pgrep kill) php-cli surf coreutils(sleep)

Usage(){
	cat <<-EOH
		${0##*/} - Manage browser (and php server if applicable)
		Usage:  show [restart|r|log|l] start|s | nolog|n | stop|kill|k
		    restart/r/log/l:  Stop and start with logging (default)
		    start/s:          Start with logging
		    nolog/n:          Start without logging
		    kill/k/stop:      Stop
		    help/h:           Show usage
		  Logging only applies when the php server is running, ignored otherwise
	EOH
}

: ${SITE:=$SITE}
: ${URL:=$URL}
[[ $URL ]] || URL="http://$SITE/index.html"
srv="/usr/bin/php -S $SITE -t $HOME/git/bulletin/web"
brw='/usr/bin/surf -bmpF'

mode=start log=1
case $1 in
help|h|-h|--help) Usage; exit 0 ;;
kill|k|stop) mode=kill ;;
nolog|n) mode=start log=0 ;;
start|s) mode=start ;;
restart|r|log|l|'') mode=restart ;;
*) Usage; exit 1
esac

if [[ $mode = kill || $mode = restart ]]
then
	[[ $SITE ]] && pkill -f "$srv" &&
		echo "Web server terminated" ||
		echo "Web server was not running"
	pkill -f  "$brw" &&
		echo "Browser terminated" ||
		echo "Browser was not running"
fi

if [[ $mode = start || $mode = restart ]]
then
	pgrep -f "$brw" &&
		echo "Browser was running already" ||
		DISPLAY=:0 $brw "$URL" &
	if pgrep -f "$srv"
	then echo "Web server was running already"
	else
		if [[ $SITE ]]
		then
			((log)) && null=$0.log || null=/dev/null
			$srv 2>>"$null" &
			pid=$!
			sleep 1
			kill -0 $pid &&
				echo "Web server started on http://$SITE" ||
				echo "Failed to start web server on http://$SITE"
		fi
	fi
fi
