#!/usr/bin/env bash
# Started by lxsession's autostart

url="%IP:%PORT"
[[ $url = %IP:%PORT ]] && echo "Change %IP and %PORT in websrv before use!" &&
	exit 1
cmd="/usr/bin/php -S $url -t $HOME/git/bulletin/web"

if [[ $1 = stop || $1 = kill ]]
then
  pkill -f "$cmd" && echo "Web server terminated" && exit 0
  echo "Web server was not running"
  exit 1
fi

pgrep -f "$cmd" && echo "Web server was running already " && exit 2

[[ $1 = log ]] && null=$0.log || null=/dev/null
$cmd 2>"$null" &
(($?)) && echo "Web server started on http://$url - terminate by: $0 stop" ||
	echo "ERROR: failed to start webserver on http://$url"
