#!/usr/bin/env bash
# displ - Turn raspberrypi display on and off
# Usage: displ [on|1 | off|0]
#   If no argument: Only on a Schoolday turn the display on
# Example crontab lines:
#     30 7 * * 1-5 /home/pi/git/bulletin/displ  # Mo-Fr 7:30 Schoolday: On
#     0 17 * * 1-5 /home/pi/git/bulletin/displ off  # Mo-Fr 17:00: Off
# Require: libraspberrypi-bin(vcgencmd) wget date grep

[[ $1 = on || $1 = 1 ]] && vcgencmd display_power 1 && exit 0
[[ $1 = off || $1 = 0 ]] && vcgencmd display_power 0 && exit 0
[[ -n $1 ]] &&
	echo -e "Usage: ${0##*/} [on|1 | off|0]\nWrong argument: '$1'" && exit 1

url='https://gitlab.com/pepa65/piring/raw/master/ringdates'
ringdates=$(wget -qO- "$url") date=$(date '+%Y-%m-%d') noschool=0
grep -q "$date$" <<<"$ringdates" && noschool=1
grep -q "$date " <<<"$ringdates" && noschool=1

d=${date:0:4}${date:5:2}${date:8:2}
for range in $(grep -o '^[^#]...-..-../....-..-..[^ ]*' <<<"$ringdates")
do ((${#range}>21)) && continue  # Not a No-school range
	r1=${range:0:4}${range:5:2}${range:8:2}
	r2=${range:11:4}${range:16:2}${range:19:2}
	((r1<=d && d<=r2)) && noschool=1
done

# Turn display on when the date is not a No-school day
((noschool)) || vcgencmd display_power 1

exit 0
