#!/usr/bin/env bash

# getaqi - Read AQI and color values from aqi.crics.asia and save them in files
# Required: wget grep

a4w=$(wget -qO- aqi.crics.asia)
[[ $a4w ]] || exit 1

dir=$(readlink -e $0) dir=${dir%/*}
echo "$a4w" |grep aqinumber | grep -o '[0-9]*' >"$dir/web/aqi.txt"
echo "$a4w" |grep -o '#...' >"$dir/web/bg.txt"

exit 0
