#!/usr/bin/env bash
set -e
# INSTALL - Install piscreen/bulletin on RPiOS
# Download: https://4e4.win/piscreen
#   (redirects to https://gitlab.com/pepa65/bulletin/raw/master/INSTALL)
# Usage:  bash INSTALL
#   If URL is specified below, 'piscreen' will show that page in the browser on
#   startup, otherwise a Google Slides URL (GSURL) needs to be specified below
#   and then 'bulletin' is served on SITE and shown in the broweser on startup:
#   those Google Slides with a header, served on IP if specified (and valid),
#   or else the IP is inferred and the PORT is as specified or 8888 (default).
# Required: sudo apt-get grep sed cron libraspberrypi-bin(vcgencmd)[displ]
#   git surf unclutter xdotool lxsession php-cli[bulletin]
#   coreutils(cd mkdir mv cp chmod head ln)

URL='https://aqi.crics.asia'
#GSURL='docs.google.com/presentation/d/e/2PACX-1vRvUDuEXVO03r8LiDLhtZHqMpqN1ByvpTYreV27QQdoT9cbZ1-xknPT-D2cYu_o8Cr6ZfsdCLJ167xI'
IP=
PORT=8888

# Check preparation
[[ $URL && $GSURL ]] &&
	echo "Abort: either specify a URL or a Google-Slide GSURL, comment one out" &&
	exit 1

[[ -z $URL && -z $GSURL ]] &&
	echo "Abort: specify either a URL or a Google-Slide GSURL" &&
	exit 2

# Install additionally required packages
! sudo apt-get install -y git surf unclutter xdotool lxsession php-cli libraspberrypi-bin &&
	echo "Abort: required packages not installed" &&
	exit 3

# Download the repo only if not called from within it
cd
home=$PWD
mkdir -p git
cd git
if [[ ! $(readlink -e $0) = $(readlink -e bulletin/INSTALL) ]]
then  # Download repo
	[[ -e bulletin ]] && mv bulletin bulletin.moved$RANDOM
	git clone 'https://gitlab.com/pepa65/bulletin'
fi
cd bulletin
repo=$PWD

# Construct the show script
[[ -f show ]] && mv show show.moved$RANDOM
cp _show show
chmod +x show
if [[ $GSURL ]]
then
	[[ -z $PORT ]] && PORT=8888
	[[ -z $IP ]] &&
		IP=$(ip a |grep -o 'inet[^ ]* [^/]*' |grep -v ' 127.' |grep -v ' ::1' |head -1) SITE=${IP##* }:$PORT
	sed -i "s@GSURL@$GSURL@" web/index.html
	sed -i "s@=\$SITE@=$SITE@" show
else
	sed -i 's@="=\$URL@=$URL@" show
fi

# Install scripts
sudo ln -sf "$repo/f5" /usr/local/bin
sudo ln -sf "$repo/displ" /usr/local/bin
sudo ln -sf "$repo/show" /usr/local/bin

# Install LXDE autostart
[[ -f autostart ]] && mv autostart autostart.moved$RANDOM
cp _autostart autostart
[[ ! $home = /home/pi ]] && sed -i "s@/home/pi@$home@" autostart
lxconfdir=$home/.config/lxsession
shopt -s nullglob
n=$(echo "$lxconfdir"/* |wc -w)
((n)) || mkdir -p "$lxconfdir/LXDE"
for d in "$lxconfdir"/*
do [[ -f "$d/autostart" ]] && mv -n "$d/autostart" "$d/autostart_orig"
	ln -sf "$repo/autostart" "$d"
done

# Install crontab
crontab - < <(crontab -l; echo -e "\n# Display On at 7:00 Mo-Fr on a schoolday\n"'0 7 * * 1-5' "$repo/displ\n\n# Display Off at 17:00 Mo-Fr\n"'0 17 * * 1-5' "$repo/displ off\n")
