#!/usr/bin/env bash
# Run by cron @reboot

mainuser=$(grep ':x:1000:1000:' /etc/passwd |cut -d':' -f1)
cmd="/usr/bin/php -S bulletin:8888 -t /home/$mainuser/git/bulletin/web"
if [[ $1 = stop || $1 = kill ]]
then
	pkill -f "$cmd" && echo "Web server terminated" && exit 0
	echo "Web server was not running"
	exit 1
fi

null=/dev/stderr
[[ -t 1 ]] && null='/dev/null' || sleep 120
pgrep -f "$cmd" && echo "Web server was running already " && exit 2
$cmd 2>$null &
echo "Web server started, terminate by: $0 stop"
